SPK_NAME = nano
SPK_VERS = 2.2.6
SPK_REV = 1
SPK_ICON = src/gnu-nano.png

STARTABLE = no

DEPENDS  = cross/${SPK_NAME}
SPK_DEPENDS = 

MAINTAINER = Jdel.org
DESCRIPTION = The 2.2 release of GNU nano continues to add some features while attempting to provide continuity to users of previous versions
DISPLAY_NAME = GNU Nano
CHANGELOG = 

HOMEPAGE = http://www.nano-editor.org/
LICENSE  = GPLv2

INSTALLER_SCRIPT = src/installer.sh
SSS_SCRIPT       = src/dsm-control.sh

INSTALL_PREFIX = /usr/local/$(SPK_NAME)

include ../../mk/spksrc.spk.mk
