PKG_NAME = which
PKG_VERS = 2.20
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = http://ftp.gnu.org/gnu/$(PKG_NAME)
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS =

HOMEPAGE = http://carlo17.home.xs4all.nl/which/
COMMENT  = which - shows the full path of (shell) commands
LICENSE  = GPL

GNU_CONFIGURE = 1
CONFIGURE_ARGS = --program-prefix=gnu-

include ../../mk/spksrc.cross-cc.mk
