SPK_NAME = audio-tools
SPK_VERS = 1.1
SPK_REV = 1
SPK_ICON = src/audio-tools.png

STARTABLE = no

DEPENDS  = cross/cuetools cross/shntool cross/lame
SPK_DEPENDS = 

SUPPORTED_ARCHS = 

MAINTAINER = Jdel.org
DESCRIPTION = Audio tools, contains cuetools, shntool with FLAC support, and LAME.
DISPLAY_NAME = Audio Tools
CHANGELOG = Added LAME

HOMEPAGE = 
LICENSE  = GNU GPL V2

INSTALLER_SCRIPT = src/installer.sh
SSS_SCRIPT       = src/dsm-control.sh

INSTALL_PREFIX = /usr/local/$(SPK_NAME)

include ../../mk/spksrc.spk.mk
